name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy-stage:
    runs-on: [self-hosted, deti-engsoft-11]

    permissions:
      contents: read

    env: 
      KEYCLOAK_IMAGE: ${{ secrets.KEYCLOAK_IMAGE }}
      KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_ADMIN }}
      KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
      KEYCLOAK_LOCAL_PORT: ${{ secrets.KEYCLOAK_LOCAL_PORT }}
      KEYCLOAK_DOCKER_PORT: ${{ secrets.KEYCLOAK_DOCKER_PORT }}
      KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
      KEYCLOAK_IMPORT_PATH: ${{ secrets.KEYCLOAK_IMPORT_PATH }}
      KC_HOSTNAME_URL: ${{ secrets.KC_HOSTNAME_URL }}

      BACKEND_LOCAL_PORT: ${{ secrets.BACKEND_LOCAL_PORT }}
      BACKEND_DOCKER_PORT: ${{ secrets.BACKEND_DOCKER_PORT }}
      SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
      SPRING_SECURITY_ISSUER_URI: ${{ secrets.SPRING_SECURITY_ISSUER_URI }}
      SPRING_SECURITY_JWK_URI: ${{ secrets.SPRING_SECURITY_JWK_URI }}

      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      PG_LOCAL_PORT: ${{ secrets.PG_LOCAL_PORT }}
      PG_DOCKER_PORT: ${{ secrets.PG_DOCKER_PORT }}

      FRONTEND_LOCAL_PORT: ${{ secrets.FRONTEND_LOCAL_PORT }}
      FRONTEND_DOCKER_PORT: ${{ secrets.FRONTEND_DOCKER_PORT }}
      VITE_BACKEND_HOST: ${{ secrets.VITE_BACKEND_HOST }}
      VITE_BACKEND_PORT: ${{ secrets.VITE_BACKEND_PORT }}
      VITE_KEYCLOAK_URL: ${{ secrets.VITE_KEYCLOAK_URL }}
      VITE_UNLAYER_PUBLIC_KEY: ${{ secrets.VITE_UNLAYER_PUBLIC_KEY }}

      MAILJET_API_USERNAME: ${{ secrets.MAILJET_API_USERNAME }}
      MAILJET_API_PASSWORD: ${{ secrets.MAILJET_API_PASSWORD }}

      VITE_FLAGSMITH_ENV_ID: ${{ secrets.VITE_FLAGSMITH_ENV_ID }}
      VITE_API_VERSION: ${{ secrets.VITE_API_VERSION }}

      MACHINE_URL: ${{ secrets.MACHINE_URL }}

      TF_VAR_backend_docker_port: ${{ secrets.BACKEND_DOCKER_PORT }}
      TF_VAR_frontend_docker_port: ${{ secrets.FRONTEND_DOCKER_PORT }}
      TF_VAR_spring_profiles_active: ${{ secrets.SPRING_PROFILES_ACTIVE }}
      TF_VAR_spring_security_issuer_uri: ${{ secrets.SPRING_SECURITY_ISSUER_URI }}
      TF_VAR_spring_security_jwk_uri: ${{ secrets.SPRING_SECURITY_JWK_URI }}
      TF_VAR_mailjet_api_username: ${{ secrets.MAILJET_API_USERNAME }}
      TF_VAR_mailjet_api_password: ${{ secrets.MAILJET_API_PASSWORD }}
      TF_VAR_vite_backend_host: ${{ secrets.VITE_BACKEND_HOST }}
      TF_VAR_vite_backend_port: ${{ secrets.VITE_BACKEND_PORT }}
      TF_VAR_vite_keycloak_url: ${{ secrets.VITE_KEYCLOAK_URL }}
      TF_VAR_vite_flagsmith_env_id: ${{ secrets.VITE_FLAGSMITH_ENV_ID }}
      TF_VAR_vite_api_version: ${{ secrets.VITE_API_VERSION }}
      TF_VAR_postgres_user: ${{ secrets.POSTGRES_USER }}
      TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
      TF_VAR_postgres_db: ${{ secrets.POSTGRES_DB }}
      TF_VAR_postgres_local_port: ${{ secrets.PG_LOCAL_PORT }}
      TF_VAR_postgres_docker_port: ${{ secrets.PG_DOCKER_PORT }}
      TF_VAR_frontend_lb_internal_port: ${{ secrets.FRONTEND_LB_INTERNAL_PORT }}
      TF_VAR_frontend_lb_external_port: ${{ secrets.FRONTEND_LB_EXTERNAL_PORT }}
      TF_VAR_backend_lb_internal_port: ${{ secrets.BACKEND_LB_INTERNAL_PORT }}
      TF_VAR_backend_lb_external_port: ${{ secrets.BACKEND_LB_EXTERNAL_PORT }}
      TF_VAR_otel_exporter_otlp_endpoint: ${{secrets.OTEL_EXPORTER_OTLP_ENDPOINT}}
      TF_VAR_otel_exporter_otlp_headers: ${{secrets.OTEL_EXPORTER_OTLP_HEADERS}}

      TF_VAR_google_project_id: ${{secrets.GOOGLE_PROJECT_ID}}
      TF_VAR_gemini_api_key: ${{secrets.GEMINI_API_KEY}}
      TF_VAR_facebook_access_token: ${{secrets.FACEBOOK_ACCESS_TOKEN}}
      TF_VAR_facebook_app_id: ${{secrets.FACEBOOK_APP_ID}}
      TF_VAR_facebook_app_secret: ${{secrets.FACEBOOK_APP_SECRET}}
      TF_VAR_facebook_page_id: ${{secrets.FACEBOOK_PAGE_ID}}
      TF_VAR_facebook_public_page_id: ${{secrets.FACEBOOK_PUBLIC_PAGE_ID}}
      TF_VAR_hubspot_access_token: ${{secrets.HUBSPOT_ACCESS_TOKEN}}

      TF_VAR_machine_url: ${{ secrets.MACHINE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Deploy using Terraform
        run: |
          cd proj
          mkdir -p backend/logs frontend/logs
          docker compose down -v --remove-orphans || true
          printenv > .env
          docker rm -f $(docker ps -aq) || true
          terraform init
          terraform apply -auto-approve
          docker system prune -a -f
